### PR TITLE
Create app wireframe

### PR DESCRIPTION
**Pull request by royarg02**
1. Changed the user profile to include the "rank XP/badge tracking system".
2. Removed Forum FAQ from the right drawer to a new screen, as it would become clumsy in smaller screens.
3. Changed the reply indicator to be a continuous line.
4. A mockup of the "private post" system. Since it is yet to be implemented in the website, it essentially shows how it _could_ be implemented in the app.
5. Also added the option to create the same in "Start a Discussion" page.

### CODE REVIEW

**Comment by faiz276482** [comment]
Creating a new post is still not the way as we discussed.
Rest looks good.
Please change that one thing and we will be good to go.

**Comment by royarg02** [comment]
Could you point out the thing which you are referring to?

**Comment by faiz276482** [comment]
Pg 13 start a discussion

**Comment by royarg02** [comment]
Yes, could you elaborate what is missing?

**Comment by faiz276482** [comment]
Nothing is missing.
The design of that page was suppose to be the same as the original proposal.

**Pull request merged**
